config/routes.rb
Rails.application.routes.draw do

  root 'customers#new'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :customers, except: [:index]
  resources :restaurants do
    resources :reservations
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true
  validates :name, length: {minimum: 2}
  validates :password,
    length: {in: 4..20, incorrect_pw_length: "password must be 4 to 20 characters"}

  has_many :reservations, dependent: :destroy
  has_many :restaurants, through: :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  validates_with ReservationValidator

  belongs_to :customer
  belongs_to :restaurant

  validates :date, presence: true
  validates :time, presence: true
  validates :phone, presence: true
  validates :party_size, presence: true
  validates :party_size, numericality:{ only_integer: true}
  validate :capacity_available

  def capacity_available
    if self.party_size
      if self.restaurant.availability(self.party_size, self.time) < 0
        errors.add(:party_size, "(Sorry, we can't accommodate a party of this size at this time)")
      end
    end
  end


end

app/models/reservation_validator.rb
class ReservationValidator < ActiveModel::Validator
  def validate(reservation)
    too_early = reservation.time < reservation.restaurant.open_time
    too_late = reservation.time > reservation.restaurant.closing_time
    reservation.errors[:open] << "The Restaurant is not open at this time" if too_early || too_late
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :customers, through: :reservations

  validates :name, presence: true


  def availability(party_size, time)
     current_capacity(time) - party_size
  end

  def time_range(restaurant)
    form_time_range = []
    time_option = restaurant.open_time
    while time_option < restaurant.closing_time
      form_time_range << time_option
      time_option = time_option+1.hour
    end
    form_time_range
  end

  def time_range_show(form_time)
    form_time.map {|time| time.strftime("%l:%M%p") }
  end

  private
  def current_capacity(time)
    if self.reservations.empty?
      capacity
    else
      capacity - reserved_capacity(time)
    end
  end

  def reserved_capacity(time)
    self.reservations.where(time: time.beginning_of_hour..time.end_of_hour).sum(:party_size)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
        redirect_to login_path
    else
        render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
    @reservations = Reservation.where(customer_id: @customer.id)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update_attributes(customer_params)
      flash[:notice] = "Account updated!"
      redirect_to restaurants_path
    else
      flash[:alert] = "Something went wrong!"
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    session[:customer_id] = nil
    flash[:notice] = "Account deleted!"
    redirect_to restaurants_path
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :email, :password, :password_confirmation, :phone)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :load_reservation, only: [:show, :edit, :update, :destroy ]
  before_action :load_restaurant, except: [:create]

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.restaurant = @restaurant
    @reservation.customer = current_customer
    if @reservation.save
      flash[:notice] = "Reservation booked!"
      redirect_to customer_path(current_customer.id)
    else
      flash[:alert] = "Error: Please try again"
      redirect_to restaurant_path(@restaurant.id)
    end
  end

  def show
  end

  def edit
  end

  def update
    @reservation.update_attributes(reservation_params)
    if @reservation.save
      flash[:notice] = "Reservation updated!"
      redirect_to customer_path(current_customer.id)
    else
      flash[:alert] = "Error: Please try again"
      render :show
    end
  end

  def destroy
    @reservation.destroy
    flash[:notice] = "Reservation deleted!"
    redirect_to customer_path(current_customer.id)
  end

  private
  def reservation_params
    params.require(:reservation).permit(:date, :time, :party_size, :phone)
  end
  def load_restaurant
    @restaurant = Restaurant.find(@reservation.restaurant_id)
  end
  def load_reservation
    @reservation ||= Reservation.find(params[:id])
  end
  def current_customer
    Customer.find(session[:customer_id])
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :get_restaurant, except: [:create, :index, :new]

  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new(restaurant_id: params[:id] )
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "#{@restaurant.name} added!"
      redirect_to restaurants_path
    else
      flash[:alert] = "Error: Please try again"
      render :new
    end
  end

  def update
    @restaurant.update_attributes(restaurant_params)
    if @restaurant.save
      flash[:notice] = "#{@restaurant.name} details updated!"
      redirect_to restaurants_path
    else
      flash[:alert] = "Error: Please try again"
      render :edit
    end
  end
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def get_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :open_time, :closing_time, :address, :capacity, :phone, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    customer = Customer.find_by(email: params[:email])
    if customer && customer.authenticate(params[:password])
      session[:customer_id] = customer.id
      session[:account_type] = customer.account_type
      redirect_to restaurants_path
    else 
      flash.now[:alert] = "Incorrect login"
      render :new
    end
  end

  def destroy
    session.delete(:customer_id)
    flash[:notice] = "Logged out!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= Customer.find_by(id: session[:customer_id])
  end
end

app/views/customers/_customer_form.html.erb
<%= form_for @customer do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.text_field :phone, placeholder: "Phone" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
  </div>
  <div>
    <%= f.submit 'Submit', class:'form_button' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<%=link_to 'Back to restaurants', restaurants_path %>
<h1>Update your profile information</h1>
<%=render "customer_form" %>

app/views/customers/new.html.erb
<div class='error-notices'>
  <% if @customer.errors.any? %>
    <% @customer.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
  <% end %>
</div>

<div class="sign_up_container">
  <h1>Sign up</h1>
  <%= render "customer_form" %>
  <p>Already signed up? <%= link_to "Sign into your account", login_path %></p>
</div>

app/views/customers/show.html.erb
<%=link_to 'Back to restaurants', restaurants_path %>
<%=link_to 'Update profile', edit_customer_path(current_user.id) %>
<section id="customer_reservations_container">
  <h2>Hi <%=@customer.name %>, you have <%=@reservations.count%> current <%="reservation".pluralize(@reservations.count)%></h2>

  <% @reservations.each do |reservation| %>
    <div class="reservation-container">
      <div class="reservation-data">
        <div><h3><%= reservation.restaurant.name %></h3></div>
        <div><%= reservation.date.strftime("%m/%d/%Y") %></div>
        <div><%= reservation.time.strftime("%l:%M%p") %></div>
        <div>Party of <%= reservation.party_size %></div>
        <div>Contact number: <%= reservation.phone %></div>
      </div>

      <div>Update Details</div> 
        <div class='error-notices'>
          <% if reservation.errors.any? %>
            <% reservation.errors.full_messages.each do |msg| %>
            <ul>
              <li><%= msg %></li>
            </ul>
            <% end %>
          <% end %>
        </div>

        <% @restaurant = Restaurant.find(reservation.restaurant_id)%>
          <%= form_for [@restaurant, reservation] do |f| %>
              <%= collection_select(:reservation, :restaurant_id, Restaurant.all, :id, :name) %>
              <%= f.date_field :date  %>
              <% dropdown = @restaurant.time_range(@restaurant) %>
              <% time_options = @restaurant.time_range_show(dropdown) %>
              <%= f.select :time, options_for_select(time_options, dropdown)%>
              <%= f.text_field :party_size, placeholder: "Party size" %>
              <%= f.text_field :phone, placeholder: "Contact phone" %>
              <%= f.submit 'Update', class:"form_button" %>
          <% end%>

        <%= link_to 'Delete Reservation', [@restaurant, reservation], method: :delete, data: {confirm: "Are you sure you want to delete this reservation?"}, class:"form_button" %>
        </div>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantManager</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-no-turbolink="true">
    <p class="flash"><%= flash[:notice] %></p>
    <p class="flash"><%= flash[:alert] %></p>
    <% if !current_user.nil? %>
      <%=link_to 'Log out', logout_path, method: :delete %>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/reservations/_update_details.html.erb
<h1>Update Details</h1>

<div class='error-notices'>
  <% if @reservation.errors.any? %>
    <% @reservation.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
  <% end %>
</div>

<%= form_for [@restaurant, @reservation] do |f| %>
  <%= collection_select(:reservation, :restaurant_id, Restaurant.all, :id, :name) %>
  <%= f.label :date %>
  <%= f.date_field :date  %>
  <% dropdown = @restaurant.time_range(@restaurant) %>
  <% time_options = @restaurant.time_range_show(dropdown) %>
  <%= f.select :time, options_for_select(time_options, dropdown)%>
  <%= f.text_field :party_size, placeholder: "Party size" %>
  <%= f.text_field :phone, placeholder: "Contact phone" %>
  <%= f.submit 'Update', class:"form_button" %>
<% end%>

app/views/reservations/show.html.erb
<%=link_to 'Back to restaurants', restaurants_path %>
<%=link_to 'See my reservations', customer_path(session[:customer_id]) %>

<div class="reservation-details-container">

  <h2>Reservation Details</h2>
  <div>
    <div><h3><%= @reservation.restaurant.name %></h3></div>
    <div><%= @reservation.date.strftime("%m/%d/%Y") %> </div>
    <div><%= @reservation.time.strftime("%l:%M%p") %>
    <div><%=@reservation.phone%></div>
    </div>
    <div><%= @reservation.party_size %></div>
  </div>

  <%= render "update_details" %>

  <%= link_to 'Delete Reservation', [@restaurant, @reservation], method: :delete, data: {confirm: "Are you sure you want to delete this reservation?"}, class:"form_button" %>
</div>

app/views/restaurants/_admin_index.html.erb
<section id="restaurants_container">
  <%= link_to 'Add a Restaurant', new_restaurant_path, class:'add_restaurant' %>

  <h2>Your restaurants</h2>

   <% @restaurants.each do |restaurant| %>
     <div class="restaurant">
         <%= link_to restaurant_path(restaurant) do %>
           <%=restaurant.name%>
         <% end %>
     </div>
   <% end %>
 </section>

app/views/restaurants/_admin_show.html.erb
<div class= "reservation-container">
  <h1><%=@restaurant.reservations.count%> <%="reservation".pluralize(@restaurant.reservations.count)%> for <%=@restaurant.name%> </h1>
  <ol>
    <% Reservation.where(restaurant_id: @restaurant.id).each do |reservation|%>
    <li class="admin-restaurant-reservation">
      <div><%=reservation.customer.name%></div>
      <div><%=reservation.date.strftime("%m/%d/%Y")%></div>
      <div><%=reservation.time.strftime("%l:%M%p")%></div>
      <div>Party of <%=reservation.party_size%></div>
      <div><%=reservation.phone%></div>
    </li>
    <%end%>
  </ol>

  <%= link_to 'Update Restaurant', edit_restaurant_path(@restaurant) %>
  <%= link_to 'Delete Restaurant', @restaurant, method: :delete,  data: {confirm: "Are you sure you want to delete this restaurant"}  %>
</div>

app/views/restaurants/_customer_index.html.erb
<%=link_to 'See my reservations', customer_path(session[:customer_id]) %>
<section id="restaurants_container">
  <h2 class="restaurant_title">Hungry? Book a table at one of our restaurants!</h2>

  <% @restaurants.each do |restaurant| %>
    <div class="restaurant">
      <%= link_to restaurant_path(restaurant) do %>
        <%=restaurant.name%>
      <% end %>
    </div>
  <% end %>
</section>

app/views/restaurants/_customer_show.html.erb
<%=link_to 'See my reservations', customer_path(session[:customer_id]) %>
  <h1> Make a Reservation </h1>

  <%= form_for [@restaurant, @reservation] do |f| %>
    <div>
      <%= f.date_field :date, class:'form_box' %>
    </div>
    <div>
      <% dropdown = @restaurant.time_range(@restaurant) %>
      <% time_options = @restaurant.time_range_show(dropdown) %>
      <%= f.select :time, options_for_select(time_options, dropdown)%>
    </div>
    <div>
      <%= f.text_field :party_size, placeholder: 'Party size' %>
    </div>
    <div">
      <%= f.text_field :phone, placeholder: "Contact phone" %>
    </div>
    <div>
      <%= f.submit 'Find a Table', :class=>"form_button" %>
    </div>
  <% end %>

  <h2 class="about-restaurant">About <%=@restaurant.name%></h2>
  <p class="restaurant-description"><%=@restaurant.description%></p>
</div>

app/views/restaurants/_restaurant.html.erb
<div class='error-notices'>
  <% if @restaurant.errors.any? %>
    <% @restaurant.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
  <% end %>
</div>

<div>
  <%= form_for @restaurant do |f| %>
    <div>
      <%= f.label :name, "Name"%><br>
      <%= f.text_field :name %>
    </div><br>
    <div>
      <%= f.label :open_time, "Opening Time"%><br>
      <%= f.time_field :open_time %>
    </div><br>
    <div>
      <%= f.label :closing_time, "Closing Time"%><br>
      <%= f.time_field :closing_time %>
    </div><br>
    <div>
      <%= f.label :capacity, "Capacity" %><br>
      <%= f.text_field :capacity %>
    </div><br>
    <div>
      <%= f.label :description, "Description" %><br>
      <%= f.text_area :description %>
    </div><br>
    <div>
      <%= f.submit 'Submit' %>
    </div>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
 <%=link_to 'Back to restaurants', restaurants_path %>

<h1> Update a Restaurant </h1>

<%= render @restaurant %>

app/views/restaurants/index.html.erb
<%=link_to 'Update profile', edit_customer_path(current_user.id) %>
<% if session[:account_type] == 'admin' %>
  <%= render "admin_index"%>
<% else %>
  <%=render "customer_index" %>
<%end%>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>
<%= render @restaurant %>

app/views/restaurants/show.html.erb
<%=link_to 'Back to restaurants', restaurants_path %>
<%=link_to 'Update profile', edit_customer_path(current_user.id) %>

<% if session[:account_type] == 'admin' %>
  <%= render "admin_show"%>
<% else %>
  <%=render "customer_show"%>
<%end%>